### PR TITLE
added ALL_TIME range

### PR DESCRIPTION
**Pull request by guarde**

### CODE REVIEW

**Comment by guarde** [comment]
didn't realise it had been 3 years since update.

**Comment by jaebradley** [comment]
@jeepies yeah it's definitely been a while since the latest update. Happy to add and update this feature if this client library is still being used.

**Comment by guarde** [comment]
ngl i just made my own npm package for it to use. very limited. would be cool to see this updated tho :)

**Comment by jaebradley** [comment]
@jeepies not a problem! I'll see what I can do

**Pull request closed without merging**
